// cards.js
const ALL_CARDS = [
  // ========== MONSTROS NORMAIS (29) ==========
  { id: 'm01', tipo: 'monstro', nome: 'Guerreiro de Pedra', atk: 1200, def: 1500, custo: 0, efeito: null },
  { id: 'm02', tipo: 'monstro', nome: 'Dragão Jovem', atk: 1800, def: 1000, custo: 0, efeito: null },
  { id: 'm03', tipo: 'monstro', nome: 'Cavaleiro Andante', atk: 1600, def: 1200, custo: 0, efeito: null },
  { id: 'm04', tipo: 'monstro', nome: 'Lobo Cinzento', atk: 1000, def: 800, custo: 0, efeito: null },
  { id: 'm05', tipo: 'monstro', nome: 'Golem de Ferro', atk: 2000, def: 2000, custo: 0, efeito: null },
  { id: 'm06', tipo: 'monstro', nome: 'Águia Celeste', atk: 1500, def: 1000, custo: 0, efeito: null },
  { id: 'm07', tipo: 'monstro', nome: 'Serpente Marinha', atk: 1700, def: 1600, custo: 0, efeito: null },
  { id: 'm08', tipo: 'monstro', nome: 'Guerreiro Orc', atk: 1900, def: 1200, custo: 0, efeito: null },
  { id: 'm09', tipo: 'monstro', nome: 'Mago Arcano', atk: 1400, def: 1000, custo: 0, efeito: null },
  { id: 'm10', tipo: 'monstro', nome: 'Dragão Ancião', atk: 2500, def: 2000, custo: 0, efeito: null },
  { id: 'm11', tipo: 'monstro', nome: 'Leão de Nemeia', atk: 2200, def: 1800, custo: 0, efeito: null },
  { id: 'm12', tipo: 'monstro', nome: 'Gárgula', atk: 1300, def: 1400, custo: 0, efeito: null },
  { id: 'm13', tipo: 'monstro', nome: 'Cavalo Alado', atk: 1700, def: 1300, custo: 0, efeito: null },
  { id: 'm14', tipo: 'monstro', nome: 'Golem de Gelo', atk: 1800, def: 2000, custo: 0, efeito: null },
  { id: 'm15', tipo: 'monstro', nome: 'Mago do Caos', atk: 1600, def: 1000, custo: 0, efeito: null },
  { id: 'm16', tipo: 'monstro', nome: 'Cavaleiro Negro', atk: 2100, def: 1500, custo: 0, efeito: null },
  { id: 'm17', tipo: 'monstro', nome: 'Elfo Arqueiro', atk: 1500, def: 1200, custo: 0, efeito: null },
  { id: 'm18', tipo: 'monstro', nome: 'Dragão Bebê', atk: 1200, def: 700, custo: 0, efeito: null },
  { id: 'm19', tipo: 'monstro', nome: 'Titã', atk: 2600, def: 2200, custo: 0, efeito: null },
  { id: 'm20', tipo: 'monstro', nome: 'Sereia', atk: 1400, def: 1600, custo: 0, efeito: null },
  { id: 'm21', tipo: 'monstro', nome: 'Centauro', atk: 1800, def: 1400, custo: 0, efeito: null },
  { id: 'm22', tipo: 'monstro', nome: 'Múmia', atk: 1000, def: 1800, custo: 0, efeito: null },
  { id: 'm23', tipo: 'monstro', nome: 'Esfinge', atk: 2300, def: 2000, custo: 0, efeito: null },
  { id: 'm24', tipo: 'monstro', nome: 'Quimera', atk: 2400, def: 1800, custo: 0, efeito: null },
  // Novos Monstros Normais (Poderosos)
  { id: 'm25', tipo: 'monstro', nome: 'Dragão Imperador', atk: 3000, def: 2500, custo: 0, efeito: null },
  { id: 'm26', tipo: 'monstro', nome: 'Colosso de Obsidiana', atk: 2800, def: 3000, custo: 0, efeito: null },
  { id: 'm27', tipo: 'monstro', nome: 'Deus da Guerra', atk: 3200, def: 2800, custo: 0, efeito: null },
  { id: 'm28', tipo: 'monstro', nome: 'Besta do Apocalipse', atk: 3500, def: 2000, custo: 0, efeito: null },
  { id: 'm29', tipo: 'monstro', nome: 'Guardião do Portão', atk: 0, def: 3500, custo: 0, efeito: null },

  // ========== MONSTROS COM EFEITO (16) ==========
  { id: 'm30', tipo: 'monstro', nome: 'Fada Curandeira', atk: 800, def: 800, custo: 0, efeito: 'quando_morre_ganha_500_vida' },
  { id: 'm31', tipo: 'monstro', nome: 'Fênix Renascida', atk: 2000, def: 1500, custo: 0, efeito: 'quando_morre_ganha_500_vida' },
  { id: 'm32', tipo: 'monstro', nome: 'Necromante Sombrio', atk: 1900, def: 1500, custo: 0, efeito: 'ao_invocar_revive_monstro' },
  { id: 'm33', tipo: 'monstro', nome: 'Ladino das Sombras', atk: 1200, def: 800, custo: 0, efeito: 'ignora_defesa_ataque_direto' },
  { id: 'm34', tipo: 'monstro', nome: 'Paladino da Luz', atk: 2500, def: 2000, custo: 0, efeito: 'ao_invocar_destroi_magia_armadilha' },
  { id: 'm35', tipo: 'monstro', nome: 'Dragão Devorador', atk: 2400, def: 1200, custo: 0, efeito: 'ganha_500_atk_ao_destruir_inimigo' },
  { id: 'm36', tipo: 'monstro', nome: 'Sábio da Floresta', atk: 500, def: 500, custo: 0, efeito: 'ao_invocar_comprar_1_carta' },
  { id: 'm37', tipo: 'monstro', nome: 'Besta de Fogo', atk: 1800, def: 1000, custo: 0, efeito: 'ao_invocar_causa_500_dano_direto' },
  { id: 'm38', tipo: 'monstro', nome: 'Rei Demônio', atk: 2800, def: 2400, custo: 0, efeito: 'dano_perfurante' },
  { id: 'm39', tipo: 'monstro', nome: 'Anjo da Guarda', atk: 1000, def: 2000, custo: 0, efeito: 'imune_a_magias' },
  { id: 'm40', tipo: 'monstro', nome: 'Mago Temporal', atk: 1500, def: 1500, custo: 0, efeito: 'ao_invocar_devolve_monstro_pra_mao' },
  { id: 'm41', tipo: 'monstro', nome: 'Guerreiro Berserker', atk: 2300, def: 0, custo: 0, efeito: 'pode_atacar_duas_vezes' },
  { id: 'm42', tipo: 'monstro', nome: 'Vampiro Nobre', atk: 2100, def: 1500, custo: 0, efeito: 'cura_vida_igual_dano_causado' },
  { id: 'm43', tipo: 'monstro', nome: 'Valquíria', atk: 2100, def: 1600, custo: 0, efeito: 'imune_a_armadilhas' },

  // ========== MAGIAS (18) ==========
  { id: 's01', tipo: 'magia', nome: 'Aumento de Fé', efeito: 'buff_500', descricao: 'Escolha 1 monstro seu, ele ganha +500 de ATK.' },
  { id: 's02', tipo: 'magia', nome: 'Aumento de Fé', efeito: 'buff_500', descricao: 'Escolha 1 monstro seu, ele ganha +500 de ATK.' },
  { id: 's03', tipo: 'magia', nome: 'Aumento de Fé', efeito: 'buff_500', descricao: 'Escolha 1 monstro seu, ele ganha +500 de ATK.' },
  { id: 's04', tipo: 'magia', nome: 'Raios de Zeus', efeito: 'destruir_inimigo', descricao: 'Destrói 1 monstro inimigo na Zona de Monstros.' },
  { id: 's05', tipo: 'magia', nome: 'Raios de Zeus', efeito: 'destruir_inimigo', descricao: 'Destrói 1 monstro inimigo na Zona de Monstros.' },
  { id: 's06', tipo: 'magia', nome: 'Barganha Divina', efeito: 'comprar_2', descricao: 'Compre 2 cartas do seu deck imediatamente.' },
  { id: 's07', tipo: 'magia', nome: 'Barganha Divina', efeito: 'comprar_2', descricao: 'Compre 2 cartas do seu deck imediatamente.' },
  { id: 's08', tipo: 'magia', nome: 'Chuva de Meteoros', efeito: 'destruir_todos_inimigos', descricao: 'Destrói todos os monstros na Zona de Monstros do oponente.' },
  { id: 's09', tipo: 'magia', nome: 'Chuva de Meteoros', efeito: 'destruir_todos_inimigos', descricao: 'Destrói todos os monstros na Zona de Monstros do oponente.' },
  { id: 's10', tipo: 'magia', nome: 'Controle Mental', efeito: 'roubar_monstro', descricao: 'Assuma o controle de 1 monstro do oponente até o final do turno.' },
  { id: 's11', tipo: 'magia', nome: 'Controle Mental', efeito: 'roubar_monstro', descricao: 'Assuma o controle de 1 monstro do oponente até o final do turno.' },
  { id: 's12', tipo: 'magia', nome: 'Poção da Vida Máxima', efeito: 'curar_2000', descricao: 'Restaura 2000 Pontos de Vida.' },
  { id: 's13', tipo: 'magia', nome: 'Espada Lendária', efeito: 'buff_1000', descricao: 'Equipe em 1 monstro seu. Ele ganha +1000 de ATK e DEF.' },
  { id: 's14', tipo: 'magia', nome: 'Espada Lendária', efeito: 'buff_1000', descricao: 'Equipe em 1 monstro seu. Ele ganha +1000 de ATK e DEF.' },
  { id: 's15', tipo: 'magia', nome: 'Tempestade Mística', efeito: 'destruir_magias_armadilhas', descricao: 'Destrói todas as Magias e Armadilhas no campo do oponente.' },
  { id: 's16', tipo: 'magia', nome: 'Sacrifício Sombrio', efeito: 'comprar_3_dano_1000', descricao: 'Compre 3 cartas, mas você perde 1000 Pontos de Vida.' },

  // ========== ARMADILHAS (16) ==========
  { id: 't01', tipo: 'armadilha', nome: 'Escudo de Atenas', efeito: 'armadilha_escudo', descricao: 'Quando o oponente atacar, mude o monstro dele para modo de Defesa e cancele o ataque.' },
  { id: 't02', tipo: 'armadilha', nome: 'Escudo de Atenas', efeito: 'armadilha_escudo', descricao: 'Quando o oponente atacar, mude o monstro dele para modo de Defesa e cancele o ataque.' },
  { id: 't03', tipo: 'armadilha', nome: 'Escudo de Atenas', efeito: 'armadilha_escudo', descricao: 'Quando o oponente atacar, mude o monstro dele para modo de Defesa e cancele o ataque.' },
  { id: 't04', tipo: 'armadilha', nome: 'Escudo de Atenas', efeito: 'armadilha_escudo', descricao: 'Quando o oponente atacar, mude o monstro dele para modo de Defesa e cancele o ataque.' },
  { id: 't05', tipo: 'armadilha', nome: 'Ira do Submundo', efeito: 'armadilha_ira', descricao: 'Quando o oponente invocar um monstro com mais de 2000 de ATK, destrua esse monstro imediatamente.' },
  { id: 't06', tipo: 'armadilha', nome: 'Ira do Submundo', efeito: 'armadilha_ira', descricao: 'Quando o oponente invocar um monstro com mais de 2000 de ATK, destrua esse monstro imediatamente.' },
  { id: 't07', tipo: 'armadilha', nome: 'Ira do Submundo', efeito: 'armadilha_ira', descricao: 'Quando o oponente invocar um monstro com mais de 2000 de ATK, destrua esse monstro imediatamente.' },
  { id: 't08', tipo: 'armadilha', nome: 'Força Espelhada', efeito: 'armadilha_destruir_atacantes', descricao: 'Quando o oponente declarar um ataque, destrua TODOS os monstros em Posição de Ataque do oponente.' },
  { id: 't09', tipo: 'armadilha', nome: 'Força Espelhada', efeito: 'armadilha_destruir_atacantes', descricao: 'Quando o oponente declarar um ataque, destrua TODOS os monstros em Posição de Ataque do oponente.' },
  { id: 't10', tipo: 'armadilha', nome: 'Cilindro Mágico', efeito: 'armadilha_refletir_dano', descricao: 'Quando um monstro do oponente atacar, cancele o ataque e cause dano igual ao ATK dele aos Pontos de Vida do oponente.' },
  { id: 't11', tipo: 'armadilha', nome: 'Cilindro Mágico', efeito: 'armadilha_refletir_dano', descricao: 'Quando um monstro do oponente atacar, cancele o ataque e cause dano igual ao ATK dele aos Pontos de Vida do oponente.' },
  { id: 't12', tipo: 'armadilha', nome: 'Julgamento Divino', efeito: 'armadilha_negar_invocacao', descricao: 'Quando o oponente invocar um monstro, negue a invocação e destrua o monstro.' },
  { id: 't13', tipo: 'armadilha', nome: 'Julgamento Divino', efeito: 'armadilha_negar_invocacao', descricao: 'Quando o oponente invocar um monstro, negue a invocação e destrua o monstro.' },
  { id: 't14', tipo: 'armadilha', nome: 'Silêncio Arcano', efeito: 'armadilha_negar_magia', descricao: 'Quando o oponente ativar uma carta Mágica, negue o efeito e destrua a carta.' },
  { id: 't15', tipo: 'armadilha', nome: 'Silêncio Arcano', efeito: 'armadilha_negar_magia', descricao: 'Quando o oponente ativar uma carta Mágica, negue o efeito e destrua a carta.' },
];